# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

def shared_pods
  pod 'Kingfisher'
end

target 'SearchApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SearchApp

  shared_pods

  target 'SearchAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SearchAppUITests' do
    # Pods for testing
  end

end
